from app.prompts.analyze_candidate_system_prompt_v1 import (
    PROMPT as ANALYZE_CANDIDATE_SYSTEM_PROMPT,
)

from app.prompts.tutor_system_prompt import (
    PROMPT as TUTOR_SYSTEM_PROMPT,
)

from app.prompts.prompts import (
    INTERVIEW_CONTROLLER_SYSTEM_PROMPT,
    QUESTION_PLANNER_SYSTEM_PROMPT,
    QUESTION_REVIEW_SYSTEM_PROMPT,
    TUTOR_SYSTEM_PROMPT,
)

__all__ = [
    "ANALYZE_CANDIDATE_SYSTEM_PROMPT",
    "TUTOR_SYSTEM_PROMPT",
    "INTERVIEW_CONTROLLER_SYSTEM_PROMPT",
    "QUESTION_PLANNER_SYSTEM_PROMPT",
    "QUESTION_REVIEW_SYSTEM_PROMPT",
    "TUTOR_SYSTEM_PROMPT",
]